# Generated by Django 5.2.6 on 2025-09-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alergeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("icono", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Carta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("qr_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Negocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="core.carta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carta",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartas",
                to="core.negocio",
            ),
        ),
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("foto", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platos",
                        to="core.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatoAlergeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alergeno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.alergeno"
                    ),
                ),
                (
                    "plato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.plato"
                    ),
                ),
            ],
            options={
                "unique_together": {("plato", "alergeno")},
            },
        ),
        migrations.AddField(
            model_name="plato",
            name="alergenos",
            field=models.ManyToManyField(
                through="core.PlatoAlergeno", to="core.alergeno"
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
            ),
        ),
        migrations.CreateModel(
            name="CategoriaTraduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traducciones",
                        to="core.categoria",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("categoria", "idioma"), name="unique_categoria_idioma"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatoTraduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("historia", models.TextField(blank=True, null=True)),
                (
                    "plato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traducciones",
                        to="core.plato",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plato", "idioma"), name="unique_plato_idioma"
                    )
                ],
            },
        ),
    ]
